kind: pipeline
type: kubernetes
name: connect-e2e-tests

steps:
- name: init-workspace
  image: alpine:latest
  commands:
    - cd /tmp
    - wget https://github.com/containous/yaegi/releases/download/v0.7.1/yaegi_v0.7.1_linux_386.tar.gz
    - tar xvzf yaegi_v0.7.1_linux_386.tar.gz yaegi
    - mv yaegi /drone/src

- name: run-e2e-tests
  image: cypress/base:ubuntu16-12.13.1
  commands:
    - execEnv=$(./yaegi bin/setEnv.go $DRONE_BRANCH)
    - eval $execEnv
    - npm install
    - $(npm bin)/cypress run
  environment:
    CYPRESS_CONNECT_DEMO_YOGA_URL: https://connect-demo-yoga-u.r536.connect.eu-west-3.k8s.fewlines.net
    CYPRESS_MAILDEV_URL: http://review-maildev.review
