version: "2.4"

services:
  tests:
    image: cypress/included:3.6.1
    working_dir: /app
    command: yarn cypress run
    env_file:
      - .env
    volumes:
      - type: bind
        source: .
        target: /app
